{% set setup_py_data = load_setup_py_data() %}
{% set python_requirement = "python" + setup_py_data['python_requires'] %}

package:
  name: ndstructs
  version: {{ setup_py_data['version'] }}

source:
  path: ..

requirements:
  build:
    - {{ python_requirement }}
    - pip
  run:
    - {{ python_requirement }}
    {% for dep in setup_py_data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

build:
  noarch: python
  script:
        - python -m pip install --no-deps --ignore-installed .

test:
  imports:
    - ndstructs
    - ndstructs.utils
  source_files:
    - tests
  requires:
    {% for dep in setup_py_data['extras_require']['dev'] %}
    - {{ dep.lower() }}
    {% endfor %}
  commands:
    - pytest .
